### ISSUE TITLE
Unexpected behaviour for decimal128

### ISSUE THREAD

**Issue by zoren** [verement/decimal-arithmetic#4]
When I run `16**0.5` using `decimal128` i get `3.999999999999999999999999999999999` and not `4.000000000000000000000000000000000` as I would have expected. I seen the same unexpected behaviour for `decimal64`

I have small failing test here:

https://github.com/zoren/decimal-arithmetic/blob/add-power-tests/test/Numeric/Decimal/OperationSpec.hs#L196

Thanks for making `decimal-arithmetic`!

**Comment by verement** [comment]
Thanks for your report.

Strictly speaking, when the `power` operation is given a non-integral exponent, [the result is allowed to be up to 1 ulp (unit in last place) in error](http://speleotrove.com/decimal/daops.html#refpower). So I believe the result for `Decimal128` is still within spec.

However, the result for `Decimal64` is 2 ulp in error, so definitely unacceptable. Commit 38695f5 should allow us to do better.

FWIW in this particular case you may find `sqrt` to be a better alternative to `(** 0.5)`.
